"""
Grid configuration loader and slot lookup.

Loads grid_config.json (generated by calibration.py) and provides:
  - Slot polygon lookup: find which slot a detected circle belongs to
    using the MAJORITY RULE (>50% of circle area must overlap a slot polygon)
  - Reference bottle positions for the dynamic calibration row
  - parse_slot_id() helper

ZZ column (col 0) is NOT present in slot_data — calibration.py never
emits ZZ entries, so detection is automatically skipped for that column.
"""

import json
import math
import cv2
import numpy as np
from pathlib import Path

from configs.config import GRID_CONFIG_FILE

# Grid line counts (must match calibration.py _N_HLINES/_N_VLINES)
_NH = 14   # 14 horizontal lines → 13 row spans  (0=ref, 1-12=samples)
_NV = 17   # 17 vertical lines   → 16 col spans  (0=ZZ,  1-15=data)


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------

class GridConfig:
    """
    Loads grid_config.json and provides spatial slot lookup.

    Attributes:
        slot_data:        {slot_id: {'coords': np.array, 'expected_level': int, 'group': str}}
        reference_slots:  {slot_id: {'coords': np.array, 'level': int, 'samples': int}}
    """

    def __init__(self, config_file=GRID_CONFIG_FILE):
        self.config_file = config_file
        self.slot_data = {}
        self.reference_slots = {}
        self.corners = None     # [[x,y]×4] TL/TR/BR/BL in full-image pixel space
        self.sample_roi = None  # [x1,y1,x2,y2] bounding box of sample rows 1-12 only
        self._load()

    def _load(self):
        path = Path(self.config_file)
        if not path.exists():
            raise FileNotFoundError(
                f"Grid config not found: {self.config_file}\n"
                "Run: python main.py --calibrate"
            )

        with open(path, 'r') as f:
            data = json.load(f)

        meta = data.get("system_metadata", {})

        # Expose calibration corners for ROI fallback
        corners_raw = meta.get("corners", None)
        if corners_raw:
            self.corners = [[float(p[0]), float(p[1])] for p in corners_raw]

        # Sample-area ROI (rows 1-12 only, excludes reference row)
        roi_raw = meta.get("sample_roi", None)
        if roi_raw and len(roi_raw) == 4:
            self.sample_roi = [int(v) for v in roi_raw]

        # Fallback: compute sample_roi from grid_pts when not saved (old JSON files)
        if self.sample_roi is None:
            gp_raw = meta.get("grid_pts")
            if gp_raw:
                gp = np.array(gp_raw, dtype=np.float64)  # (14, 17, 2)
                sample_pts = gp[1:14, :, :]               # rows 1-12
                self.sample_roi = [
                    int(np.min(sample_pts[:, :, 0])),  # x1
                    int(np.min(sample_pts[:, :, 1])),  # y1
                    int(np.max(sample_pts[:, :, 0])),  # x2
                    int(np.max(sample_pts[:, :, 1])),  # y2
                ]

        for slot_id, info in data['reference_row']['slots'].items():
            self.reference_slots[slot_id] = {
                'coords': np.array(info['coords'], dtype=np.float32),
                'level':   info['level'],
                'samples': info['samples'],
            }

        for slot_id, info in data['main_grid']['slot_data'].items():
            self.slot_data[slot_id] = {
                'coords':         np.array(info['coords'], dtype=np.float32),
                'expected_level': info['expected_level'],
                'group':          info['group'],
            }

        # Homography: full-image corners → canonical rectangle.
        # Used by find_slot_for_bbox_warped() to normalise perspective before
        # slot assignment (cv2.getPerspectiveTransform).
        self._H    = None   # 3×3 float32 homography matrix, or None
        self._H_w  = 0      # width  of canonical (warped) rectangle in pixels
        self._H_h  = 0      # height of canonical (warped) rectangle in pixels
        if self.corners and len(self.corners) == 4:
            tl, tr, br, bl = [np.array(c, dtype=np.float32) for c in self.corners]
            w = int((np.linalg.norm(tr - tl) + np.linalg.norm(br - bl)) / 2)
            h = int((np.linalg.norm(bl - tl) + np.linalg.norm(br - tr)) / 2)
            if w > 0 and h > 0:
                src = np.float32([tl, tr, br, bl])
                dst = np.float32([[0, 0], [w, 0], [w, h], [0, h]])
                self._H   = cv2.getPerspectiveTransform(src, dst)
                self._H_w = w
                self._H_h = h

    # ------------------------------------------------------------------
    # Slot assignment
    # ------------------------------------------------------------------

    def find_slot_for_circle(self, cx, cy, radius):
        """
        Majority-rule assignment: find which sample slot contains the majority
        (>50%) of the circle's footprint area.

        Args:
            cx, cy:  Circle center (pixels)
            radius:  Circle radius (pixels)

        Returns:
            (slot_id, overlap_ratio) or (None, 0.0) if no majority match.
        """
        cx, cy, radius = int(cx), int(cy), int(radius)
        circle_area = np.pi * radius * radius
        if circle_area == 0:
            return None, 0.0

        best_slot    = None
        best_overlap = 0.0

        for slot_id, info in self.slot_data.items():
            coords = info['coords']
            pts    = coords.reshape(-1, 1, 2)

            # Fast pre-check: is circle center inside the polygon?
            dist = cv2.pointPolygonTest(pts, (float(cx), float(cy)), False)

            # Only compute expensive raster overlap when center is close
            if dist < -radius:
                continue   # Circle completely outside

            overlap_px    = _circle_polygon_overlap(cx, cy, radius, coords)
            overlap_ratio = overlap_px / circle_area

            if overlap_ratio > best_overlap:
                best_overlap = overlap_ratio
                best_slot    = slot_id

        if best_overlap > 0.5:   # Majority rule: >50% of circle in this slot
            return best_slot, best_overlap

        return None, 0.0

    def find_slot_for_bbox(
        self,
        x1: int, y1: int, x2: int, y2: int,
        img_shape: tuple | None = None,
        min_ioa: float = 0.30,
    ) -> tuple:
        """
        Assign a YOLO bounding box to the grid slot with the maximum
        Intersection over Bbox Area (IoA). Uses rasterised polygon masks.

        Parameters
        ----------
        x1, y1, x2, y2 : int
            Bounding box corners in full-image pixel coordinates.
        img_shape : (height, width), optional
            Used for tie-breaking: the slot whose centroid is closer to the
            image centre wins (compensates for outward perspective lean).
        min_ioa : float, default 0.30
            Minimum IoA required to accept the assignment. Detections below
            this threshold are treated as false positives / ghost bottles.

        Returns
        -------
        (slot_id, ioa)
            slot_id : str | None — winning slot, or None if IoA < min_ioa
            ioa     : float 0-1  — Intersection / BboxArea of winning slot
        """
        x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
        bbox_area = (x2 - x1) * (y2 - y1)
        if bbox_area <= 0:
            return None, 0.0

        best_slot    : str | None = None
        best_overlap : int        = 0
        ties         : list       = []

        for slot_id, info in self.slot_data.items():
            overlap = _bbox_polygon_overlap(x1, y1, x2, y2, info["coords"])
            if overlap == 0:
                continue
            if overlap > best_overlap:
                best_overlap = overlap
                best_slot    = slot_id
                ties         = [(slot_id, overlap)]
            elif overlap == best_overlap:
                ties.append((slot_id, overlap))

        if best_slot is None:
            return None, 0.0

        # IoA filter — reject ghost / noise detections
        ioa = best_overlap / bbox_area
        if ioa < min_ioa:
            return None, 0.0

        # Tie-breaking: slot centroid closer to image centre wins
        if len(ties) > 1 and img_shape is not None:
            ih, iw = img_shape
            img_cx, img_cy = iw / 2.0, ih / 2.0

            def _dist_to_centre(sid: str) -> float:
                c = self.slot_data[sid]["coords"]
                return math.hypot(
                    float(np.mean(c[:, 0])) - img_cx,
                    float(np.mean(c[:, 1])) - img_cy,
                )

            best_slot = min((sid for sid, _ in ties), key=_dist_to_centre)

        return best_slot, ioa

    def find_slot_for_bbox_warped(
        self,
        x1: int, y1: int, x2: int, y2: int,
        min_ioa: float = 0.30,
    ) -> tuple:
        """
        Perspective-normalised slot assignment via homography.

        1. Transform the four corners of the YOLO bbox through the
           homography H (computed from grid corners → canonical rectangle
           via cv2.getPerspectiveTransform at load time).
        2. In the canonical (undistorted) space, each grid cell is a
           perfect rectangle — IoA reduces to simple AABB arithmetic.
        3. Return the cell with maximum IoA if IoA >= min_ioa.
        4. Ties: prefer the cell whose centre is closest to the image centre
           in the canonical space (counteracts lens distortion).

        Returns (None, 0.0) when:
          - No homography is available (corners not saved in grid_config.json)
          - Best IoA is below min_ioa (false-positive / ghost filter)

        Parameters
        ----------
        x1, y1, x2, y2 : int   Bbox in full-image pixel coordinates.
        min_ioa         : float Minimum IoA to accept (default 0.30).

        Returns
        -------
        (slot_id, ioa)
            slot_id : str | None
            ioa     : float 0-1
        """
        if self._H is None:
            return None, 0.0

        # Warp all four bbox corners through H, take bounding rect of result
        pts_img = np.float32([
            [x1, y1], [x2, y1], [x2, y2], [x1, y2]
        ]).reshape(-1, 1, 2)
        pts_warp = cv2.perspectiveTransform(pts_img, self._H).reshape(-1, 2)
        nx1 = float(np.min(pts_warp[:, 0]))
        ny1 = float(np.min(pts_warp[:, 1]))
        nx2 = float(np.max(pts_warp[:, 0]))
        ny2 = float(np.max(pts_warp[:, 1]))

        bbox_area = (nx2 - nx1) * (ny2 - ny1)
        if bbox_area <= 0:
            return None, 0.0

        # Canonical cell dimensions (uniform grid in warped space)
        cell_w = self._H_w / (_NV - 1)
        cell_h = self._H_h / (_NH - 1)

        best_slot : str | None = None
        best_ioa  : float      = 0.0
        ties      : list       = []

        for r in range(_NH - 1):
            for c in range(_NV - 1):
                sid = _canonical_slot_id(r, c)
                if sid is None:
                    continue
                # Cell bounds in canonical space
                cx1 = c * cell_w;  cy1 = r * cell_h
                cx2 = cx1 + cell_w; cy2 = cy1 + cell_h
                # AABB intersection
                ix1 = max(nx1, cx1); iy1 = max(ny1, cy1)
                ix2 = min(nx2, cx2); iy2 = min(ny2, cy2)
                inter = max(0.0, ix2 - ix1) * max(0.0, iy2 - iy1)
                if inter == 0:
                    continue
                ioa = inter / bbox_area
                if ioa > best_ioa:
                    best_ioa  = ioa
                    best_slot = sid
                    ties      = [(sid, ioa)]
                elif ioa == best_ioa:
                    ties.append((sid, ioa))

        if best_slot is None or best_ioa < min_ioa:
            return None, 0.0

        # Tie-breaking: canonical cell centre closer to canonical image centre
        if len(ties) > 1:
            img_cx = self._H_w / 2.0
            img_cy = self._H_h / 2.0

            def _canonical_dist(sid: str) -> float:
                r_idx, c_idx = _slot_id_to_rc(sid)
                scx = (c_idx + 0.5) * cell_w
                scy = (r_idx + 0.5) * cell_h
                return math.hypot(scx - img_cx, scy - img_cy)

            best_slot = min((sid for sid, _ in ties), key=_canonical_dist)

        return best_slot, best_ioa

    def assign_bbox(
        self,
        x1: int, y1: int, x2: int, y2: int,
        img_shape: tuple | None = None,
        min_ioa: float = 0.30,
    ) -> tuple:
        """
        Unified entry point for bbox-to-slot assignment.

        Uses calibrated polygon overlap (bilinear grid_pts from grid_config.json),
        which is consistent with the settings canvas labels.

        Returns
        -------
        (slot_id, ioa)  — slot id and intersection-over-area fraction.
        """
        return self.find_slot_for_bbox(x1, y1, x2, y2, img_shape, min_ioa)

    # ------------------------------------------------------------------
    # Reference positions
    # ------------------------------------------------------------------

    def get_reference_positions(self):
        """
        Return individual bottle positions within each reference slot polygon.

        Each REF_Lx polygon in grid_config.json is one wide rectangle covering
        3 physical reference bottles side by side.  Dividing it into 3 equal
        vertical thirds gives one sampling centre per bottle — much more accurate
        than a single centroid that averages over all three bottles and the gaps
        between them.

        Returns:
            dict {level (int): [(cx, cy, radius), ...]}
            Each list contains exactly 3 entries (one per reference bottle).
        """
        positions = {}
        for slot_id, info in self.reference_slots.items():
            level  = info['level']
            coords = info['coords']

            x_min = float(np.min(coords[:, 0]))
            x_max = float(np.max(coords[:, 0]))
            y_min = float(np.min(coords[:, 1]))
            y_max = float(np.max(coords[:, 1]))

            cy    = int((y_min + y_max) / 2)
            r     = max(1, int((y_max - y_min) / 2))   # radius = half cell height

            # Divide wide polygon into 3 equal vertical thirds
            width = x_max - x_min
            for i in range(3):
                cx = int(x_min + (i + 0.5) * width / 3)
                positions.setdefault(level, []).append((cx, cy, r))

        return positions


# ---------------------------------------------------------------------------
# Geometry helpers
# ---------------------------------------------------------------------------

def _circle_polygon_overlap(cx, cy, radius, polygon_coords):
    """
    Approximate the overlap area (pixels) between a circle and a polygon
    using rasterized binary masks.

    Args:
        cx, cy:          Circle center (int)
        radius:          Circle radius (int)
        polygon_coords:  (N, 2) float32 array of polygon vertices

    Returns:
        Overlap area in pixels (float).
    """
    pts   = polygon_coords.astype(np.int32)
    x_min = max(0, int(np.min(pts[:, 0])) - 1)
    y_min = max(0, int(np.min(pts[:, 1])) - 1)
    x_max = int(np.max(pts[:, 0])) + 1
    y_max = int(np.max(pts[:, 1])) + 1

    w = x_max - x_min + 1
    h = y_max - y_min + 1
    if w <= 0 or h <= 0:
        return 0.0

    poly_mask = np.zeros((h, w), dtype=np.uint8)
    shifted   = pts - np.array([x_min, y_min], dtype=np.int32)
    cv2.fillPoly(poly_mask, [shifted.reshape(-1, 1, 2)], 255)

    circle_mask = np.zeros((h, w), dtype=np.uint8)
    cv2.circle(circle_mask, (cx - x_min, cy - y_min), radius, 255, -1)

    intersection = cv2.bitwise_and(poly_mask, circle_mask)
    return float(cv2.countNonZero(intersection))


def _canonical_slot_id(r: int, c: int):
    """
    Return the slot_id for grid cell (row_span r, col_span c), or None.

    Row spans:  0 = reference row (skip), 1-12 = sample rows
    Col spans:  0 = ZZ dead zone (skip), 1-15 = data columns
    """
    if c == 0 or r == 0 or r > 12 or c > 15:
        return None
    group_num = math.ceil(r / 3)          # 1-4
    level_idx = (c - 1) // 3             # 0-4
    wgr       = (r - 1) % 3             # within-group row  0-2
    wbc       = (c - 1) % 3             # within-block col  0-2
    slot_num  = wgr * 3 + wbc + 1       # 1-9
    return f"A{group_num}{slot_num}_{level_idx}"


def _slot_id_to_rc(slot_id: str):
    """
    Reverse of _canonical_slot_id — returns (row_span, col_span).
    Used for tie-breaking centroid distance in warped space.
    """
    g  = int(slot_id[1])                         # group 1-4
    s  = int(slot_id[2])                         # slot  1-9
    l  = int(slot_id.split("_")[1])              # level 0-4
    wgr = (s - 1) // 3                           # within-group row
    wbc = (s - 1) % 3                            # within-block col
    r   = (g - 1) * 3 + wgr + 1                 # row span 1-12
    c   = l * 3 + wbc + 1                        # col span 1-15
    return r, c


def _bbox_polygon_overlap(x1: int, y1: int, x2: int, y2: int,
                           polygon_coords: np.ndarray) -> int:
    """
    Pixel-level intersection area between a bounding-box rectangle and a
    polygon, using rasterized binary masks (same technique as
    _circle_polygon_overlap).

    Returns overlap pixel count (0 if no intersection).
    """
    pts    = polygon_coords.astype(np.int32)
    px_min = max(0, int(np.min(pts[:, 0])) - 1)
    py_min = max(0, int(np.min(pts[:, 1])) - 1)
    px_max = int(np.max(pts[:, 0])) + 1
    py_max = int(np.max(pts[:, 1])) + 1

    w = px_max - px_min + 1
    h = py_max - py_min + 1
    if w <= 0 or h <= 0:
        return 0

    # Fast AABB reject — if bbox and polygon bounding rect don't overlap, skip
    if x2 <= px_min or x1 >= px_max or y2 <= py_min or y1 >= py_max:
        return 0

    poly_mask = np.zeros((h, w), dtype=np.uint8)
    shifted   = pts - np.array([px_min, py_min], dtype=np.int32)
    cv2.fillPoly(poly_mask, [shifted.reshape(-1, 1, 2)], 255)

    bbox_mask = np.zeros((h, w), dtype=np.uint8)
    bx1 = max(0, x1 - px_min)
    by1 = max(0, y1 - py_min)
    bx2 = min(w - 1, x2 - px_min)
    by2 = min(h - 1, y2 - py_min)
    if bx2 > bx1 and by2 > by1:
        cv2.rectangle(bbox_mask, (bx1, by1), (bx2, by2), 255, -1)

    return int(cv2.countNonZero(cv2.bitwise_and(poly_mask, bbox_mask)))


# ---------------------------------------------------------------------------
# Grid layout table
# ---------------------------------------------------------------------------

def load_grid_layout(txt_path=None):
    """
    Load main-grid cell names from a CSV-like text file (e.g. table/a.txt).

    File format:
      Line 0  — header row (skipped)
      Lines 1+ — one row per grid row; comma-separated cell names
                 Cell 0 is always "ZZ" (dead zone, kept for column alignment)

    Returns:
        list[list[str]] — rows top-to-bottom, each row is a list of cell names
                          (col 0 = "ZZ").
    """
    if txt_path is None:
        txt_path = Path(__file__).parent / "table" / "a.txt"
    rows = []
    for line in Path(txt_path).read_text().splitlines()[1:]:  # skip header
        line = line.strip()
        if line:
            rows.append([c.strip() for c in line.split(',')])
    return rows


# ---------------------------------------------------------------------------
# Slot ID helpers
# ---------------------------------------------------------------------------

def parse_slot_id(slot_id):
    """
    Parse a slot ID string into its components.

    Format: A{group_num}{slot_num}_{level}
    Example: 'A25_3' → {'group': 'A2', 'slot': 5, 'expected_level': 3}

    Args:
        slot_id: str like 'A25_3'

    Returns:
        dict with keys 'group', 'slot', 'expected_level'
    """
    group         = "A" + slot_id[1]
    slot          = int(slot_id[2])
    expected_level = int(slot_id.split("_")[1])
    return {"group": group, "slot": slot, "expected_level": expected_level}
