"""
Grid configuration loader and slot lookup.

Loads grid_config.json (generated by calibration.py) and provides:
  - Slot polygon lookup: find which slot a detected circle belongs to
    using the MAJORITY RULE (>50% of circle area must overlap a slot polygon)
  - Reference bottle positions for the dynamic calibration row
  - parse_slot_id() helper

ZZ column (col 0) is NOT present in slot_data — calibration.py never
emits ZZ entries, so detection is automatically skipped for that column.
"""

import json
import cv2
import numpy as np
from pathlib import Path

from configs.config import GRID_CONFIG_FILE


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------

class GridConfig:
    """
    Loads grid_config.json and provides spatial slot lookup.

    Attributes:
        slot_data:        {slot_id: {'coords': np.array, 'expected_level': int, 'group': str}}
        reference_slots:  {slot_id: {'coords': np.array, 'level': int, 'samples': int}}
    """

    def __init__(self, config_file=GRID_CONFIG_FILE):
        self.config_file = config_file
        self.slot_data = {}
        self.reference_slots = {}
        self._load()

    def _load(self):
        path = Path(self.config_file)
        if not path.exists():
            raise FileNotFoundError(
                f"Grid config not found: {self.config_file}\n"
                "Run: python main.py --calibrate"
            )

        with open(path, 'r') as f:
            data = json.load(f)

        for slot_id, info in data['reference_row']['slots'].items():
            self.reference_slots[slot_id] = {
                'coords': np.array(info['coords'], dtype=np.float32),
                'level':   info['level'],
                'samples': info['samples'],
            }

        for slot_id, info in data['main_grid']['slot_data'].items():
            self.slot_data[slot_id] = {
                'coords':         np.array(info['coords'], dtype=np.float32),
                'expected_level': info['expected_level'],
                'group':          info['group'],
            }

    # ------------------------------------------------------------------
    # Slot assignment
    # ------------------------------------------------------------------

    def find_slot_for_circle(self, cx, cy, radius):
        """
        Majority-rule assignment: find which sample slot contains the majority
        (>50%) of the circle's footprint area.

        Args:
            cx, cy:  Circle center (pixels)
            radius:  Circle radius (pixels)

        Returns:
            (slot_id, overlap_ratio) or (None, 0.0) if no majority match.
        """
        cx, cy, radius = int(cx), int(cy), int(radius)
        circle_area = np.pi * radius * radius
        if circle_area == 0:
            return None, 0.0

        best_slot    = None
        best_overlap = 0.0

        for slot_id, info in self.slot_data.items():
            coords = info['coords']
            pts    = coords.reshape(-1, 1, 2)

            # Fast pre-check: is circle center inside the polygon?
            dist = cv2.pointPolygonTest(pts, (float(cx), float(cy)), False)

            # Only compute expensive raster overlap when center is close
            if dist < -radius:
                continue   # Circle completely outside

            overlap_px    = _circle_polygon_overlap(cx, cy, radius, coords)
            overlap_ratio = overlap_px / circle_area

            if overlap_ratio > best_overlap:
                best_overlap = overlap_ratio
                best_slot    = slot_id

        if best_overlap > 0.5:   # Majority rule: >50% of circle in this slot
            return best_slot, best_overlap

        return None, 0.0

    # ------------------------------------------------------------------
    # Reference positions
    # ------------------------------------------------------------------

    def get_reference_positions(self):
        """
        Return centroid positions of reference slot polygons grouped by level.

        Returns:
            dict {level (int): [(cx, cy, radius), ...]}
            Each list has REFS_PER_LEVEL (3) entries in practice after calibration
            generates one wide polygon per REF_Lx. We treat the polygon centroid
            as the single sampling center for that level group.
        """
        positions = {}
        for slot_id, info in self.reference_slots.items():
            level  = info['level']
            coords = info['coords']

            cx = int(np.mean(coords[:, 0]))
            cy = int(np.mean(coords[:, 1]))

            # Approximate radius from polygon half-width
            w = int((np.max(coords[:, 0]) - np.min(coords[:, 0])) / 2)
            h = int((np.max(coords[:, 1]) - np.min(coords[:, 1])) / 2)
            radius = max(1, min(w, h))

            positions.setdefault(level, []).append((cx, cy, radius))

        return positions


# ---------------------------------------------------------------------------
# Geometry helpers
# ---------------------------------------------------------------------------

def _circle_polygon_overlap(cx, cy, radius, polygon_coords):
    """
    Approximate the overlap area (pixels) between a circle and a polygon
    using rasterized binary masks.

    Args:
        cx, cy:          Circle center (int)
        radius:          Circle radius (int)
        polygon_coords:  (N, 2) float32 array of polygon vertices

    Returns:
        Overlap area in pixels (float).
    """
    pts   = polygon_coords.astype(np.int32)
    x_min = max(0, int(np.min(pts[:, 0])) - 1)
    y_min = max(0, int(np.min(pts[:, 1])) - 1)
    x_max = int(np.max(pts[:, 0])) + 1
    y_max = int(np.max(pts[:, 1])) + 1

    w = x_max - x_min + 1
    h = y_max - y_min + 1
    if w <= 0 or h <= 0:
        return 0.0

    poly_mask = np.zeros((h, w), dtype=np.uint8)
    shifted   = pts - np.array([x_min, y_min], dtype=np.int32)
    cv2.fillPoly(poly_mask, [shifted.reshape(-1, 1, 2)], 255)

    circle_mask = np.zeros((h, w), dtype=np.uint8)
    cv2.circle(circle_mask, (cx - x_min, cy - y_min), radius, 255, -1)

    intersection = cv2.bitwise_and(poly_mask, circle_mask)
    return float(cv2.countNonZero(intersection))


# ---------------------------------------------------------------------------
# Grid layout table
# ---------------------------------------------------------------------------

def load_grid_layout(txt_path=None):
    """
    Load main-grid cell names from a CSV-like text file (e.g. table/a.txt).

    File format:
      Line 0  — header row (skipped)
      Lines 1+ — one row per grid row; comma-separated cell names
                 Cell 0 is always "ZZ" (dead zone, kept for column alignment)

    Returns:
        list[list[str]] — rows top-to-bottom, each row is a list of cell names
                          (col 0 = "ZZ").
    """
    if txt_path is None:
        txt_path = Path(__file__).parent / "table" / "a.txt"
    rows = []
    for line in Path(txt_path).read_text().splitlines()[1:]:  # skip header
        line = line.strip()
        if line:
            rows.append([c.strip() for c in line.split(',')])
    return rows


# ---------------------------------------------------------------------------
# Slot ID helpers
# ---------------------------------------------------------------------------

def parse_slot_id(slot_id):
    """
    Parse a slot ID string into its components.

    Format: A{group_num}{slot_num}_{level}
    Example: 'A25_3' → {'group': 'A2', 'slot': 5, 'expected_level': 3}

    Args:
        slot_id: str like 'A25_3'

    Returns:
        dict with keys 'group', 'slot', 'expected_level'
    """
    group         = "A" + slot_id[1]
    slot          = int(slot_id[2])
    expected_level = int(slot_id.split("_")[1])
    return {"group": group, "slot": slot, "expected_level": expected_level}
