#!/usr/bin/env bash
# setup-server.sh — One-command setup for the Urine Analyzer server (Ubuntu)
# Run from the project root:  bash scripts/setup-server.sh
set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── 0. Must be run from project root ─────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"
info "Project root: $PROJECT_DIR"

# ── 1. Verify this is NOT a Raspberry Pi ─────────────────────────────────────
ARCH="$(uname -m)"
if [[ "$ARCH" == "aarch64" ]]; then
    error "Detected aarch64 (Raspberry Pi). Use scripts/setup-pi.sh instead."
    exit 1
fi
info "Architecture: $ARCH ✓"

# ── 2. Check Python ≥ 3.11 ───────────────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
    error "python3 not found. Install Python 3.11+ first."
    exit 1
fi
PY_VER="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
PY_MAJOR="${PY_VER%%.*}"
PY_MINOR="${PY_VER##*.}"
if (( PY_MAJOR < 3 || (PY_MAJOR == 3 && PY_MINOR < 11) )); then
    error "Python $PY_VER found but 3.11+ is required."
    exit 1
fi
info "Python $PY_VER ✓"

# ── 3. Install uv if missing ──────────────────────────────────────────────────
if ! command -v uv &>/dev/null; then
    info "uv not found — installing..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    # shellcheck disable=SC1090
    source "$HOME/.local/bin/env" 2>/dev/null || true
    export PATH="$HOME/.local/bin:$PATH"
fi
UV_PATH="$(command -v uv)"
info "uv: $UV_PATH ✓"

# ── 4. Install server dependencies ───────────────────────────────────────────
info "Installing dependencies (server + common)..."
"$UV_PATH" sync --extra server --extra common

# ── 5. Create required directories ───────────────────────────────────────────
info "Creating directories..."
mkdir -p logs logs/img server/static/results credentials

# ── 6. Create .env if not present ────────────────────────────────────────────
if [[ -f ".env" ]]; then
    warn ".env already exists — skipping creation. Edit manually if needed."
else
    info "Creating .env..."

    # Generate a random API key as default
    DEFAULT_KEY="$(openssl rand -hex 16 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(16))')"

    echo ""
    echo "─────────────────────────────────────────────"
    echo "  Configuration"
    echo "─────────────────────────────────────────────"
    read -rp "  API_KEY     [default: $DEFAULT_KEY]: " INPUT_KEY
    API_KEY="${INPUT_KEY:-$DEFAULT_KEY}"

    read -rp "  DATABASE_URL [default: sqlite:///logs/urine_analysis.db]: " INPUT_DB
    DATABASE_URL="${INPUT_DB:-sqlite:///logs/urine_analysis.db}"

    cat > .env <<EOF
# Urine Analyzer — Server environment
# Generated by scripts/setup-server.sh

# Auth token — must match the Pi's API_KEY
API_KEY=${API_KEY}

# Database connection (SQLite default; swap for PostgreSQL in production)
DATABASE_URL=${DATABASE_URL}

# Pi client URL — not used on the server, left for reference
# SERVER_URL=http://localhost:8000
EOF

    info ".env created."
    echo ""
    warn "Remember to copy API_KEY to the Pi's .env file."
fi

# ── 7. Write and install systemd service ─────────────────────────────────────
SERVICE_NAME="urine-server"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

info "Writing systemd unit to $SERVICE_FILE..."
sudo tee "$SERVICE_FILE" > /dev/null <<EOF
[Unit]
Description=Urine Analyzer — Server
After=network.target
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
Type=simple
User=${USER}
WorkingDirectory=${PROJECT_DIR}
EnvironmentFile=${PROJECT_DIR}/.env
ExecStart=${UV_PATH} run python main.py --role server
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

[Install]
WantedBy=multi-user.target
EOF

# ── 8. Enable and start the service ──────────────────────────────────────────
info "Enabling and starting $SERVICE_NAME..."
sudo systemctl daemon-reload
sudo systemctl enable --now "$SERVICE_NAME"

# ── 9. Print status ───────────────────────────────────────────────────────────
echo ""
sudo systemctl status "$SERVICE_NAME" --no-pager || true
echo ""
info "Setup complete!"
echo ""
echo "  Useful commands:"
echo "    systemctl status  $SERVICE_NAME"
echo "    systemctl restart $SERVICE_NAME"
echo "    journalctl -u $SERVICE_NAME -f"
echo ""
echo "  Web UI: http://$(hostname -I | awk '{print $1}'):8000/upload"
