#!/usr/bin/env bash
# setup-pi.sh — One-command setup for the Urine Analyzer Pi client
# Run from the project root:  bash scripts/setup-pi.sh
set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── 0. Must be run from project root ─────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"
info "Project root: $PROJECT_DIR"

# ── 1. Verify this IS a Raspberry Pi (aarch64) ───────────────────────────────
ARCH="$(uname -m)"
if [[ "$ARCH" != "aarch64" ]]; then
    error "Detected $ARCH — this script is for Raspberry Pi (aarch64) only."
    error "For the Ubuntu server use scripts/setup-server.sh instead."
    exit 1
fi
info "Architecture: $ARCH ✓"

# ── 2. Check Python ≥ 3.11 ───────────────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
    error "python3 not found. Install Python 3.11+ first:"
    error "  sudo apt install python3.11 python3.11-venv"
    exit 1
fi
PY_VER="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
PY_MAJOR="${PY_VER%%.*}"
PY_MINOR="${PY_VER##*.}"
if (( PY_MAJOR < 3 || (PY_MAJOR == 3 && PY_MINOR < 11) )); then
    error "Python $PY_VER found but 3.11+ is required."
    exit 1
fi
info "Python $PY_VER ✓"

# ── 3. Install uv if missing ──────────────────────────────────────────────────
if ! command -v uv &>/dev/null; then
    info "uv not found — installing..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    # shellcheck disable=SC1090
    source "$HOME/.local/bin/env" 2>/dev/null || true
    export PATH="$HOME/.local/bin:$PATH"
fi
UV_PATH="$(command -v uv)"
info "uv: $UV_PATH ✓"

# ── 4. Install Pi dependencies ────────────────────────────────────────────────
info "Installing dependencies (pi + common)..."
"$UV_PATH" sync --extra pi --extra common

# ── 5. Enable I2C (for LCD display) ──────────────────────────────────────────
info "Enabling I2C interface..."
if command -v raspi-config &>/dev/null; then
    sudo raspi-config nonint do_i2c 0
    info "I2C enabled ✓"
else
    warn "raspi-config not found — enable I2C manually via: sudo raspi-config → Interface Options → I2C"
fi

# ── 6. Enable camera ─────────────────────────────────────────────────────────
info "Enabling camera interface..."
if command -v raspi-config &>/dev/null; then
    sudo raspi-config nonint do_camera 0 2>/dev/null || \
        sudo raspi-config nonint do_legacy_camera 0 2>/dev/null || \
        warn "Camera enable step skipped (may already be enabled or using libcamera)"
    info "Camera enabled ✓"
else
    warn "raspi-config not found — ensure 'start_x=1' is set in /boot/config.txt"
fi

# ── 7. Add user to hardware access groups ────────────────────────────────────
GROUPS_ADDED=0
for GRP in gpio i2c video spi; do
    if getent group "$GRP" &>/dev/null; then
        if ! id -nG "$USER" | grep -qw "$GRP"; then
            sudo usermod -aG "$GRP" "$USER"
            info "Added $USER to group: $GRP"
            GROUPS_ADDED=1
        else
            info "Already in group $GRP ✓"
        fi
    fi
done

# ── 8. Create .env if not present ────────────────────────────────────────────
if [[ -f ".env" ]]; then
    warn ".env already exists — skipping creation. Edit manually if needed."
else
    info "Creating .env..."
    echo ""
    echo "─────────────────────────────────────────────"
    echo "  Configuration"
    echo "─────────────────────────────────────────────"

    read -rp "  API_KEY (must match server): " API_KEY
    while [[ -z "$API_KEY" ]]; do
        warn "API_KEY cannot be empty."
        read -rp "  API_KEY (must match server): " API_KEY
    done

    read -rp "  SERVER_URL (e.g. https://abc.trycloudflare.com): " SERVER_URL
    while [[ -z "$SERVER_URL" || "$SERVER_URL" == "http://localhost:8000" ]]; do
        warn "SERVER_URL must be a real server address (not localhost)."
        read -rp "  SERVER_URL: " SERVER_URL
    done

    cat > .env <<EOF
# Urine Analyzer — Pi Client environment
# Generated by scripts/setup-pi.sh

# Auth token — must match the server's API_KEY
API_KEY=${API_KEY}

# Server address (Cloudflare tunnel URL or LAN IP)
SERVER_URL=${SERVER_URL}
EOF

    info ".env created."
fi

# ── 9. Create required directories ───────────────────────────────────────────
info "Creating directories..."
mkdir -p logs

# ── 10. Write and install systemd service ────────────────────────────────────
SERVICE_NAME="urine-pi"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

info "Writing systemd unit to $SERVICE_FILE..."
sudo tee "$SERVICE_FILE" > /dev/null <<EOF
[Unit]
Description=Urine Analyzer — Pi Client
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
Type=simple
User=${USER}
WorkingDirectory=${PROJECT_DIR}
EnvironmentFile=${PROJECT_DIR}/.env
ExecStart=${UV_PATH} run python main.py --role client
Restart=always
RestartSec=15
KillMode=process
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

[Install]
WantedBy=multi-user.target
EOF

# ── 11. Enable and start the service ─────────────────────────────────────────
info "Enabling and starting $SERVICE_NAME..."
sudo systemctl daemon-reload
sudo systemctl enable --now "$SERVICE_NAME"

# ── 12. Print status and advice ──────────────────────────────────────────────
echo ""
sudo systemctl status "$SERVICE_NAME" --no-pager || true
echo ""
info "Setup complete!"
echo ""
echo "  Useful commands:"
echo "    systemctl status  $SERVICE_NAME"
echo "    systemctl restart $SERVICE_NAME"
echo "    journalctl -u $SERVICE_NAME -f"
echo ""

if (( GROUPS_ADDED )); then
    warn "New hardware group memberships will take effect after you log out and back in."
    warn "If the service fails with GPIO permission errors, reboot: sudo reboot"
fi
